# Generated by Django 2.2.3 on 2019-10-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastapp', '0002_album_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='files',
        ),
    ]
